packages:
  - packages/**

gitChecks: false
strictPeerDependencies: true
saveExact: true
dedupePeers: true

allowBuilds:
  esbuild: false
  unrs-resolver: false

# in line with https://github.com/containerbase/.github/blob/main/default.json,
# all non-Renovate or non-Containerbase packages should only be installed after
# 3 days
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@renovatebot/*'
  - '@containerbase/*'
